### ISSUE TITLE
Service ignore my custom function name

### ISSUE THREAD

**Issue by ceth-x86** [ervitis/gohealthchecker#1]
Hi,

First of all thanks for your library. I am playing with it and I think I found a little mistake. Here is my code:

```go
health := gohealthchecker.NewHealthchecker(http.StatusOK, http.StatusInternalServerError)
health.Add(anotherCheck(), "one")
```
Here is JSON which I got:

```json
{
  "info": [
    {
      "message": "dial tcp :8185: connect: connection refused",
      "code": 500,
      "service": "anotherCheck"
    }
  ],
  "code": 500
}
```

I got name of function on the `service` field of JSON instead of my second parameter - "one".

`Add()` function is a variadic functions and second parameter is a slice. So [when we are trying to cast slice to string](https://github.com/ervitis/gohealthchecker/blob/master/healthchecker.go#L103) we always get the empty string.

If you don't mind I could create pull request to fix it.

**Comment by ervitis** [comment]
Sure! Thank you so much

**Comment by ervitis** [comment]
Ok, I have seen the error. I am writing some comments in the PR, so let's move there! :)

**Comment by ervitis** [comment]
I will close this :)
